### ISSUE TITLE
Plugsuit Permission Every Hour?

### ISSUE THREAD

**Issue by QaziPython** [rwu823/afloat#1]
Does plugsuit ask for permission every hour?

**Comment by rwu823** [comment]
@Rafeh01 
May you post more informations?
I don't have installed `plugsuit` on my OSX, let me try it later.

**Comment by rwu823** [comment]
Hi @Rafeh01 
This is from PlugSuit's introduction, I think your problem get here?
 
> Important warning:PlugSuit replaces SIMBL. Do not use them together. Choose one and use it exclusively. If SIMBL is installed, **PlugSuit will automatically do nothing to preserve stability**.
