### ISSUE TITLE
afloat does not work!

### ISSUE THREAD

**Issue by elwingh** [rwu823/afloat#11]
EI Capitan 10.11.2 afloat does not work!!

**Comment by Megashape** [comment]
Indeed, doesn't work for me either!

**Comment by rwu823** [comment]
Is it like the issue #7?

**Comment by elwingh** [comment]
yes！Afloat does not work on any native OSX apps！

**Comment by mrpatricko** [comment]
Didn't work for me either. OSX 10.11.3

**Comment by madvas** [comment]
yep, no success with 10.11.3

**Comment by mrpatricko** [comment]
Actually, this ended up working for me, but only for a couple apps. Certainly not the native apps I was hoping for.
