### ISSUE TITLE
Afloat.bundle was not able to copy to Plugins folder

### ISSUE THREAD

**Issue by delvin5** [rwu823/afloat#12]
Afloat.bundle was not able to copy to /Library/Application Support/SIMBL/Plugins using the script. I went through /src/installer-afloat.zip on github, then copy/paste Afloat.bundle manually. After that it worked well on OS version 10.10.5.

**Comment by rwu823** [comment]
@delvin5 

The script doesn't copy to `/Library` It should copy to `~/Library`.

https://github.com/rwu823/afloat/blob/master/install.sh#L11
