### ISSUE TITLE
10.11.2

### ISSUE THREAD

**Issue by Peter-Odd** [rwu823/afloat#14]
Hi, I tried this on an OS X 10.11.2 installation, unfortunately it doesn't seem to work on that version :(. 
I did as follows:
curl https://raw.githubusercontent.com/rwu823/aflot/master/install.sh | sh
and rebooted.

**Comment by rwu823** [comment]
@Peter-Odd 
Did you install EasySIMBL at the time? It may causes conflict with SIMBL. May you try to removeEasySIMBL?

**Comment by Peter-Odd** [comment]
I missed that error yesterday, but the copy -R row failed due to missing / after Afloat.bundle:
cp -R ./Afloat.bundle ~/Library/Application\ Support/SIMBL/Plugins;
should be
cp -R ./Afloat.bundle/ ~/Library/Application\ Support/SIMBL/Plugins;
on my computer.

Error message:
p: cannot overwrite directory /Users/user/Library/Application Support/SIMBL/Plugins/Afloat.bundle/Contents/Resources/en.lproj/Afloat.nib with non-directory Afloat.bundle/Contents/Resources/en.lproj/Afloat.nib

I tried it manually with /, and it copies as it should, but the always on top option doesn't seem to appear after reboot.

**Comment by Peter-Odd** [comment]
Tried it once more and now I have Afloat for iTerm2, but no other app. Is this the way it should be? or should every application have the Afloat-options?
Thank you

**Comment by rwu823** [comment]
@Peter-Odd 

`Afloat` doesn't work with any apps. please see https://github.com/rwu823/afloat/issues/7#issuecomment-155525651
