### ISSUE TITLE
Doesn't work on 10.11.4

### ISSUE THREAD

**Issue by Namor-Votilav** [rwu823/afloat#19]
Sadly, afloat didn't show up after the reboot.

**Comment by rwu823** [comment]
OH!? Does it work fine before you upgrade to `10.11.4`?

**Comment by Namor-Votilav** [comment]
I have installed it just today, haven't used it before.

**Comment by rwu823** [comment]
Did you check #15  ?

**Comment by Namor-Votilav** [comment]
Will try this, thanks :+1:
