### ISSUE TITLE
Uninstalling afloat

### ISSUE THREAD

**Issue by ebalassanian** [rwu823/afloat#22]
I'm having a hard time uninstalling this pluging (it's crashing xcode for me). I tried removing all the related files in the application support directory, but I'm still having sporadic crashes in xcode 7 with reports that the afloat plugin is the cause. Anyone else having similar issues? Advice on how to completely uninstall?

**Comment by rwu823** [comment]
It just remove `~/Library/Application\ Support/SIMBL/Plugins/Afloat.bundle`

**Comment by geligelu** [comment]
This doesn't really "uninstall" afloat. As opposed to just removing access to the bundle in SIMBL.

Any other more complete uninstallation?

**Comment by rwu823** [comment]
Do you want do remove `SIMBL` totally, too?

**Comment by geligelu** [comment]
Yes.

**Comment by rwu823** [comment]
You may try [UninstallPKG](https://www.corecode.at/uninstallpkg/)
