### ISSUE TITLE
cant see afloat menu items

### ISSUE THREAD

**Issue by saneman** [rwu823/afloat#23]
ran script installed fine, but no new menu items after reboot in Terminal

**Comment by rwu823** [comment]
try to find solution #7 and #15

**Comment by saneman** [comment]
sorted, needed to close ALL terminals,

Thanks for the quick reply


gUY


On Fri, May 6, 2016 at 10:25 AM, Rocky Wu <notifications@github.com> wrote:

> try to find solution #7 <https://github.com/rwu823/afloat/issues/7> and
> #15 <https://github.com/rwu823/afloat/issues/15>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/rwu823/afloat/issues/23#issuecomment-217380866>
>



-- 
gUY

**Comment by rwu823** [comment]
Great, let's close this :)
