### ISSUE TITLE
doesn't work on preview/notes/pages

### ISSUE THREAD

**Issue by CaptainLu** [rwu823/afloat#24]
I've tester it on several apps, it appears to work only on some of them, i.e. safari, system preferences, Xcode.. I saw a grey written "Float on top" on notes though, is it built-in? How can I activate it?
<img width="287" alt="screen shot 2016-05-12 at 21 56 41" src="https://cloud.githubusercontent.com/assets/18305506/15228428/73d85ff4-188c-11e6-8988-1a3525e27eab.png">

**Comment by rwu823** [comment]
Yes, unfortunate afloat doesn't work for all apps
