### ISSUE TITLE
Awesome

### ISSUE THREAD

**Issue by rjdamore** [rwu823/afloat#28]
You made this so darn easy! I appreciate very much the work you have done to make Afloat something I have no issue installing. Instead of something I loathe having to install. 👍 Thank you!

**Comment by rwu823** [comment]
Enjoy it 💯 :)

**Comment by shadycloud** [comment]
Agreed. Thank you very much. 
You get the first star I've ever given anyone on GitHub. I was a bit worried that something bad might happen if I tried this but I couldn't resist giving it a go.
Indeed, terminal is Afloat over my IDE for c programming this semester!      

>I'm using El Capitan 10.11.3

**Comment by rwu823** [comment]
What did you mean about something bad?

**Comment by shadycloud** [comment]
I don't know much about installing stuff in terminal and disabling SIP.

**Comment by rwu823** [comment]
You should goole and learn the knowledge, it's not this project's business :)
