### ISSUE TITLE
Afloat doesn't work for Firefox (sip disabled)

### ISSUE THREAD

**Issue by iliakan** [rwu823/afloat#29]
For Chrome, Window has the "Keep Afloat".

For Firefox, Window has nothing like that.

Any way to fix?

**Comment by rwu823** [comment]
Afloat doesn't support each app.

**Comment by iliakan** [comment]
Thank you very much for the answer. Sure, I understand. Could you please

**Comment by rwu823** [comment]
I'm not the Afloat's author, this project is just created for quickly install. you could check the post #7 discussion.
