### ISSUE TITLE
Unable to install on OS X 10.11

### ISSUE THREAD

**Issue by Spokane-Dude** [rwu823/afloat#3]
Followed your instructions and this is what I get trying to install on OS X 10.11:

Last login: Sat Oct 17 09:03:55 on console
iMac:~ spokanedude$ curl https://raw.githubusercontent.com/rwu823/aflot/master/install.sh | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   448  100   448    0     0    240      0  0:00:01  0:00:01 --:--:--   240
sh: line 2: wget: command not found
rm: SIMBL-0.9.9.pkg: No such file or directory
rm: installer-afloat.zip: No such file or directory

Do I need to install SIMBL?

**Comment by rwu823** [comment]
Hi @Spokane-Dude 

You don't need to install `SIMBL` first.
I have try to fix this issue, please try again.

Thanks for your report :)

**Comment by rwu823** [comment]
Should be fixed, close it.
