### ISSUE TITLE
Afloat blocks The Unarchiver

### ISSUE THREAD

**Issue by akira-okumura** [rwu823/afloat#34]
When Afloat is enabled on El Capitan, The Unarchiver 3.11.1 does not work. Please see this issue report.
https://github.com/jsdf/theunarchiver/issues/583

**Comment by thiagoveloso** [comment]
This issue with The Unarchiver also affects me - Sierra (10.12.1) with mySIMBL and @rwu823 's Afloat.

**Comment by rwu823** [comment]
I have no idea how to fix that, perhaps it is an issue of `The Unarchiver`.
