### ISSUE TITLE
A little bug in script

### ISSUE THREAD

**Issue by piotrros** [rwu823/afloat#4]
mv ./Afloat.bundle ~/Library/Application\ Support/SIMBL/Plugins;

I'm getting error that it's a directory and cannot be renamed.

Instead it can be done with these 2 lines:

cp -R ./Afloat.bundle ~/Library/Application\ Support/SIMBL/Plugins;
rm -rf ./Afloat.bundle

**Comment by rwu823** [comment]
yeah `cp -R` is better, It has been fix now.
