### ISSUE TITLE
Does not appear to install in 10.11

### ISSUE THREAD

**Issue by MikeMig** [rwu823/afloat#5]
The terminal command appears to go through and after I enter my password the installation reports completed. When I then look at the windows command, I don't see the afloat commands. I have re-booted twice and tried to re-install twice. Still nothing.

**Comment by rwu823** [comment]
@MikeMig 
May you check the path is it exists `Afloat.bundle`?

      ~/Library/Application\ Support/SIMBL/Plugins

**Comment by MikeMig** [comment]
The directory exists, but is empty.

**Comment by Jasperrr91** [comment]
Same problem as MikeMig, the plugins folder remains empty.

**Comment by rwu823** [comment]
I was trying uninstall and re install through script, still work fine for me on 10.11. not sure what is the actual problems for you. But the SIMBL plugin have two locate:

The one is at root
```sh
/Library/Application\ Support/SIMBL/Plugins
```

another is at User's Home directory
```
~/Library/Application\ Support/SIMBL/Plugins
```

The root locate should be empty, and User's Home directory should have `Afloat.bundle `

**Comment by MikeMig** [comment]
Ok. I see the one in the user directory.

**Comment by Jasperrr91** [comment]
So do I, problem might be OS related as I'm running 10.10.3.

**Comment by rwu823** [comment]
Please also see the comments in #7

**Comment by MikeMig** [comment]
Thank you. So it appears that afloat does not work on the native apps. The afloat commands do show up on other apps. I just confirmed that they show up on Spotify. Do you think you will be able to make it work with the native apps?
