### ISSUE TITLE
afloat does not work on EI Capitan

### ISSUE THREAD

**Issue by auralia22** [rwu823/afloat#7]
Hi,

I upgraded from Yosemite to EI Capitan.
Before upgrade, afloat worked well using EasySimbl.

After upgrade, I removed EasySimbl and run the following command on terminal.

> > curl https://raw.githubusercontent.com/rwu823/aflot/master/install.sh | sh

But afloat does not work.

Could you help me?

Thanks,
Ross

**Comment by rwu823** [comment]
Hi Ross

Do you try rebook or reopen app ?

**Comment by auralia22** [comment]
Yes I tried reboot and reopen.

**Comment by auralia22** [comment]
Hi,

I found one thing.

Afloat works well on new installed application after I install it.
But it does not work on Safari or Chrome.

Thanks,
Ross

**Comment by rwu823** [comment]
@auralia22  Hi  Ross

It's so strange. May you help me try reinstall Chrome or some apps?

**Comment by auralia22** [comment]
Thanks, it works on chrome.

But it does not work on mac default apps - safari, quicktime viewer, etc

Thanks,
Ross

**Comment by rwu823** [comment]
I think this problem is `Afloat` original doesn't full support for each app. I will research for other alternative .

**Comment by auralia22** [comment]
Thank you!

**Comment by sanjeevverma1** [comment]
Afloat does not work on any native OSX apps. However, Afloat will run on any other third-party app (Spotify, Chrome, Omnifocus, etc.), even if you are running the latest beta of El Capitan.

**Comment by rwu823** [comment]
@sanjeevverma1  Thanks for the detail explain :+1:

**Comment by bleepktch** [comment]
I'm pretty positive that Afloat used to work on native OS X apps. I used to do some tricky video stuff with my desktop using it where I had a fullscreen screen cap window open and I would use keep afloat on the Finder which would make these really trip visuals with the finder and desktop feeding back into it self into infinity. I have a video of it somewhere. Will post a link if I can find it

**Comment by mastergberry** [comment]
Can confirm this. Just tried running it on 10.11.2 and it's not working either. I used to use this with Facetime all the time back on 10.9.3 It was the primary purpose for me. I had to upgrade my mac recently to 10.11.2 because I had to send it off to Apple Support for a repair.

**Comment by bleepktch** [comment]
Didn't there also used to be an option to keep things in the background? I might be imagining that one.

**Comment by bleepktch** [comment]
Also interestingly Alfoat does work with Apple apps that are not natively installed, eg. Xcode

**Comment by MoOx** [comment]
Not working for me. It's probably related to the system integrity shit.

**Comment by MoOx** [comment]
That might help https://github.com/norio-nomura/EasySIMBL/issues/26#issuecomment-117028426

**Comment by brunorsini** [comment]
Hi everyone,

On El Capitan Afloat is working great for me on some apps: VLC, iTerm, Sublime Text, etc.

It's not working on Apple apps (eg, Facetime... huge bummer on that one!) but I guess that's normal.

However, I'd love it to work on Chrome and Spotify and some people here seem to have accomplished this. Can you please confirm / share any tips you might have that made it work on those two apps? I don't have permission to install EasySIMBL on this machine but wonder if that's related at all...

**Comment by carconper** [comment]
Hello,

First of all thanks for the contribution.
Sadly I have not been able to make it work with 10.11.3. I am not able to see the options on the Windows menu not for the native Apple apps nor for the rest of 3rd party applications.

I have gone through the issues posted here and checked tried most of the things. The only thing i haven't done yet is disabling SIP as I have read it doest work either.

Is there anything else I can try?

If not, can you share the instructions to cleanly and completely uninstall everything that the scripts installs?

Thanks a lot for your time and effort.

**Comment by arvindstutzen** [comment]
it will be great if Afloat work for Facetime

**Comment by sanjeevverma1** [comment]
Disable SIP. Add Afloat bundle to plugins and apps support folder in user library. This should work for all native OSX apps. 


-- 
Sanjeev Verma

**Comment by arvindstutzen** [comment]
@sanjeevverma1  Forgot to mention was in Mac OSX Yosemite 10.10 is there any way to work in it

**Comment by lionel-** [comment]
Just to confirm that this works perfectly:

- disabling SIP
- installing afloat again with @rwu823's great script
- and restarting the Apple applications.

Works with Safari at least.

**Comment by brunorsini** [comment]
Does anyone please know whether disabling SIP has any meaningful side
effects?

**Comment by lionel-** [comment]
Didn't look too much into it. It leaves your computer a bit more vulnerable I guess but not more so than before El Capitan.

One side effect of having SIP enabled is that you can't modify anything in `/usr/` except `/usr/local/`. Even if you're root. Not being able to modify `/usr/bin/` makes life a bit more difficult so that was one more reason to disable SIP.

**Comment by sanjeevverma1** [comment]
Disabling SIP makes everything work @brunorsini

**Comment by ldong** [comment]
SIP is the killer of such good app.

**Comment by iliakan** [comment]
It doesn't work for Firefox. Why? Can there be a workaround?

**Comment by jitendravyas** [comment]
I installed it and disabled SIP. I think it doesn't work with any app on my mac. I'm on Sierra

**Comment by jitendravyas** [comment]
Does it work on Sierra for anyone?

**Comment by rwu823** [comment]
@jitendravyas 

https://github.com/rwu823/afloat#macos-sierra-solution and #30

**Comment by MrSumor** [comment]
OSX 10.12.6 , can't use it, Why?
